/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    paletteName: "Pink Marble",
    id: "pink-marble",
    colors: [
      { color: "#D96690" },
      { color: "#F28DBC" },
      { color: "#F2C9E0" },
      { color: "#89C2D9" },
      { color: "#88E8F2" },
    ],
  },
  {
    paletteName: "Sun",
    id: "sun",
    colors: [
      { color: "#F2E205" },
      { color: "#F2CB05" },
      { color: "#F29F05" },
      { color: "#F2620F" },
      { color: "#CE4010" },
    ],
  },
  {
    paletteName: "Warm Contrast",
    id: "warm contrast",
    colors: [
      { color: "#e84a4a" },
      { color: "#fb7756" },
      { color: "#facd60" },
      { color: "#fdfa66" },
      { color: "#1ac0c6" },
    ],
  },
  {
    paletteName: "Material UI Colors",
    id: "material-ui-colors",
    colors: [
      { color: "#F44336" },
      { color: "#E91E63" },
      { color: "#9C27B0" },
      { color: "#673AB7" },
      { color: "#3F51B5" },
      { color: "#2196F3" },
    ],
  },
  {
    paletteName: "Flat Colors",
    id: "flat-ui-colors-v1",
    colors: [
      { color: "#1abc9c" },
      { color: "#2ecc71" },
      { color: "#3498db" },
      { color: "#9b59b6" },
      { color: "#34495e" },
      { color: "#16a085" },
    ],
  },
  {
    paletteName: "Dutch",
    id: "dutch",
    colors: [
      { color: "#FFC312" },
      { color: "#C4E538" },
      { color: "#12CBC4" },
      { color: "#FDA7DF" },
      { color: "#ED4C67" },
      { color: "#F79F1F" },
    ],
  },
  {
    paletteName: "American",
    id: "american",
    colors: [
      { color: "#55efc4" },
      { color: "#81ecec" },
      { color: "#74b9ff" },
      { color: "#a29bfe" },
      { color: "#dfe6e9" },
      { color: "#00b894" },
    ],
  },
  {
    paletteName: "Aussie",
    id: "aussie",
    colors: [
      { color: "#f6e58d" },
      { color: "#ffbe76" },
      { color: "#ff7979" },
      { color: "#badc58" },
      { color: "#dff9fb" },
      { color: "#f9ca24" },
    ],
  },
  {
    paletteName: "Candy",
    id: "candy",
    colors: [
      { color: "#70d6ff" },
      { color: "#ff70a6" },
      { color: "#ff9770" },
      { color: "#ffd670" },
      { color: "#e9ff70" },
    ],
  },
  {
    paletteName: "British",
    id: "british",
    colors: [
      { color: "#00a8ff" },
      { color: "#9c88ff" },
      { color: "#fbc531" },
      { color: "#4cd137" },
      { color: "#487eb0" },
      { color: "#0097e6" },
    ],
  },
  {
    paletteName: "Nature",
    id: "nature",
    colors: [
      { color: "#0785F2" },
      { color: "#0A6ABF" },
      { color: "#35BDF2" },
      { color: "#8DE8F2" },
      { color: "#94F250" },
    ],
  },
  {
    paletteName: "Spanish",
    id: "spanish",
    colors: [
      { color: "#40407a" },
      { color: "#706fd3" },
      { color: "#f7f1e3" },
      { color: "#34ace0" },
      { color: "#33d9b2" },
      { color: "#2c2c54" },
    ],
  },
  {
    paletteName: "Indian",
    id: "indian",
    colors: [
      { color: "#FEA47F" },
      { color: "#25CCF7" },
      { color: "#EAB543" },
      { color: "#55E6C1" },
      { color: "#CAD3C8" },
      { color: "#F97F51" },
    ],
  },
  {
    paletteName: "Pastel Dreams",
    id: "pastel-dreams",
    colors: [
      { color: "#FFAEBC" },
      { color: "#A0E7E5" },
      { color: "#B4F8C8" },
      { color: "#FBE7C6" },
    ],
  },
  {
    paletteName: "French",
    id: "french",
    colors: [
      { color: "#fad390" },
      { color: "#f8c291" },
      { color: "#6a89cc" },
      { color: "#82ccdd" },
      { color: "#b8e994" },
      { color: "#f6b93b" },
    ],
  },
];
